# The URL the site will be built for
base_url = "https://allietran.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# theme = "zola-resume"
theme = "DeepThought"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Allie Tran"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_links_target_blank = true

[extra]
# Put all your custom variables here

navbar_items = [
 { code = "en", nav_items  = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/cv", name = "CV" },
	{ url = "$BASE_URL/publications", name = "Publications" },
	{ url = "$BASE_URL/projects", name = "Projects" },
	{ url = "$BASE_URL/art", name = "Art" },
  ]}
]

[extra.author]
name = "Allie Tran"
avatar = "/images/17 copy.jpg"
avatar2 = "/images/me-dracula.png"

[extra.social]
github = "allie-tran"
linkedin = "allie-tran-343a86169"
orcid = "0000-0002-9597-1832"
google_scholar = "FWVnlZkAAAAJ"
dblp = "267/2642"

[extra.favicon]
favicon_16x16 = "/favicon/favicon-16x16.png"
favicon_32x32 = "/favicon/favicon-32x32.png"
webmanifest = "/favicon/site.webmanifest"
apple_touch_icon = "/favicon/apple-touch-icon.png"
android_chrome_192x192 = "/favicon/android-chrome-192x192.png"
android_chrome_512x512 = "/favicon/android-chrome-512x512.png"
